### ISSUE TITLE
Default compression settings of 10.0 trigger bug in AWS API Gateway server

### ISSUE THREAD

**Issue by rez10191** [python-websockets/websockets#1065]
Hello,

I've noticed an issue that appears to have started with websockets version 10.0.  I have a websocket server run by the [AWS API gateway](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-overview.html).  I use the websockets library to connect with my python program.  Under 9.1 there was no issue receiving messages, but I noticed that as of 10.0 I stopped receiving the messages the server continuously sends (verified through `wscat`).  

When I run with the logger I'd observe the connection being made as expected:

`async with websockets.connect(my_url) as websocket:`

```
DEBUG, > Upgrade: websocket
DEBUG, > Connection: Upgrade
DEBUG, > Sec-WebSocket-Key: cSPm5HYtYSZU3BoudrY91w==
DEBUG, > Sec-WebSocket-Version: 13
DEBUG, > Sec-WebSocket-Extensions: permessage-deflate; server_max_window_bits=12; client_max_window_bits=12
DEBUG, > User-Agent: Python/3.7 websockets/10.0
DEBUG, < HTTP/1.1 101 Switching Protocols
DEBUG, < Date: Wed, 06 Oct 2021 17:57:43 GMT
DEBUG, < Connection: upgrade
DEBUG, < upgrade: websocket
DEBUG, < sec-websocket-accept: e9Ztme4JDr4o30+FPAUZwoJMZcE=
DEBUG, < sec-websocket-extensions: permessage-deflate;server_max_window_bits=12
DEBUG, = connection is OPEN
```
Note that the server does not reply with any compression options.  I *think* this is valid if the server doesn't support compression.

I then wait on messages like so:

```
while True:
    msg = await websocket.recv()
```

Everything appears normal from a connection perspective, except messages should be flowing regularly instead of just default ping / pong style responses:
```
DEBUG, %% sending keepalive ping
DEBUG, > PING 3c 93 7f 61 [binary, 4 bytes]
DEBUG, < PONG 3c 93 7f 61 [binary, 4 bytes]
```

I discovered if I set `compression=None` in `connect` ie:

```
async with websockets.connect(my_url, compression=None) as websocket:
```

Then messages from my server flow as usual as they did in `9.1`.

It seems like compression should be something AWS supports on their side and will also engage with their support.  However, since things appear to work with `wscat`, I think there may also be an issue with the `websockets` library itself in supporting servers that do not support compression.

To help debugging, I'm hosting a websocket server through the API Gateway which outputs regular messages to any connected client and does not require any authentication.  I won't guarantee it will stay up indefinitely (sorry to any future readers!)

To test, run:
`wscat -c  wss://n36vwxc045.execute-api.us-east-2.amazonaws.com/test`
This should work and you'll see the output `< {"thanks": "for investigating this"}` at about 1/2 Hz.

If you use the following code with the websockets `10.0` library to read the messages:
```
import asyncio
import websockets
import socket

import logging

logging.basicConfig(
    format="%(message)s",
    level=logging.DEBUG,
)

def main() -> None:
    asyncio.get_event_loop().run_until_complete(
        listen_forever(
            "wss://n36vwxc045.execute-api.us-east-2.amazonaws.com/test"
        )
    )


async def listen_forever(
    url: str
) -> None:
    """
    Listen for a websocket message, reconnecting if something bad happens.

    Args:
      url (str): The URL to which to connect.

    """
    # outer loop restarted every time the connection fails
    while True:
        try:
            async with websockets.connect(
                url,
                # compression=None  # UNCOMMENT THIS LINE TO GET MESSAGES
            ) as websocket:
                print('Websocket connected, waiting for messages...')
                while True:
                    msg = await websocket.recv()
                    print(msg)
        except socket.gaierror as exp:
            print(exp)
            continue
        except ConnectionRefusedError as exp:
            print(exp)
            continue
        except websockets.exceptions.ConnectionClosedOK:
            print(
                'Server closed connection (2 hour timeout?), reconnecting.'
            )
            continue
        except websockets.exceptions.InvalidStatusCode as exp:
            print(
                'Server returned an InvalidStatusCode - {}. Reconnecting.'.format(
                    exp
                )
            )
            continue
        except asyncio.streams.IncompleteReadError as exp:
            print(
                'Server an IncompleteReadError - {}. Reconnecting.'.format(
                    exp
                )
            )
            continue
        except Exception as exp:
            print(
                'Unhandled exception - {}. Reconnecting.'.format(
                    exp
                )
            )
            continue


if __name__ == '__main__':
    main()
```

You'll observe no message output unless you uncomment line 35.

Thanks for all your great work on this project!

**Comment by aaugustin** [comment]
An incompatibility between websockets and AWS API Gateway would explain why this problem affects several independent services.

**Comment by rez10191** [comment]
Thanks for the quick response.  Looks like I mixed up the meaning of ">" and "<" when I read through this and jumped to a conclusion about the underlying issue : )   Updated the title, but left the original issue text.

Let me know if there is anything else I can help with, much appreciated.

**Comment by aaugustin** [comment]
I tried posting to the AWS forums: https://forums.aws.amazon.com/thread.jspa?threadID=346730

**Comment by aaugustin** [comment]
Yes, I believe wscat either doesn't attempt to do compression at all, or does it without specifying optimized parameters that trigger the bug.

**Comment by aaugustin** [comment]
The problem we are hitting here mainly affects clients. Memory consumption of clients is usually not a big deal, as you don't tend to open thousands of client connections from the same computer.

So I'm thinking to drop the memory optimization for clients 😢  and keep it only for servers. Then the "out of the box" experience with AWS API Gateway would work.

**Comment by ekreutz** [comment]
Great work with the library!

Just dropping in to say that I, too, had issues with the new release. Had to spend a few hours debugging my client code to figure out the the compression parameters were causing problems.

I'm hoping you can find a good compromise with better default settings, even if in this case the real problem is at AWS!

Note: perhaps the release notes could mention this? I was scratching my head as to why `9.1` was working and `10.0` was not, even if none of the changes in the changelog could have caused it.

**Comment by aaugustin** [comment]
@adriansev This makes a difference of 250kB / connection. So, not a deal breaker compared to the memory footprint of a Python interpreter, and you can always disable compression to save memory.

@ekreutz Unfortunately, the 10.0 release notes are tied to the 10.0 git tag, so it's a bit difficult to add more content there after the fact :-(

**Comment by aaugustin** [comment]
#1067 implements my proposal to drop the memory optimization for clients and keep it for servers.

**Comment by aaugustin** [comment]
I'm going to wait a bit to see if AWS fixes it on their end, now that they know about it, before morging that.

**Comment by aaugustin** [comment]
Well done! That's more than I was able to get on my end! If they get it from multiple sources, there's hope :-)

**Comment by aaugustin** [comment]
I don't want to sound overly pessimistic but, in order to fall down, it would have to be on their priority pile in the first place... ;-)

**Comment by rez10191** [comment]
FYI: Got a new reply back on my case today:

> Firstly I would like to apologize for the delay in getting back to you.
> 
> Yes you are right, API Gateway accepts Permesage-deflate extension. I made some more tests regarding this issue at my end and observed that irrespective of the value, API Gateway will fail(PING/PONG) when “server_max_window_bits” is passed.
> 
> Moving ahead, I provided my findings along with your queries to the API Gateway Service team. The team has mentioned that they identified this issue as a bug at API Gateway side. Also, we have a feature request implementation for the same in place. However, due to the limited visibility into the progress of the team’s internal development processes, unfortunately, I won't be able to provide an ETA for the same.  However, I can assure you that our internal team takes customers feedback very seriously and are always looking at ways to improve the services. Meanwhile, I would kindly request you to keep an eye on the What's New Page and AWS Blogs to know more about the future releases:
> 
> [+]What's New: https://aws.amazon.com/new/ 
> [+]AWS Blogs: https://aws.amazon.com/blogs/aws/ 

So maybe hopefully some wheels turning on their side too.

**Comment by scottbelden** [comment]
@aaugustin Are you planning to make a minor release that includes the removed optimization? While I'm not connecting to a crypto server, my code does make connections to some other poorly implemented websocket server and is hitting the same NegotiationError. A minor release would probably help prevent other people from opening new issues about the same common problem.

**Comment by aaugustin** [comment]
Yes, I'm planning to make a minor release by the end of the year.

**Comment by aaugustin** [comment]
Version 10.1 is available on PyPI.
