### ISSUE TITLE
Can implement parallel processing when the client receives messages？

### ISSUE THREAD

**Issue by mujinbao** [python-websockets/websockets#1071]
In my scenario, the server will broadcast messages to multiple clients at a high rate. The server sends more than 60 messages to the client per second
As mentioned above, some clients have to process all data per second in real time, but others have a processing speed of only 30 messages per second, so these 60 messages will still be broadcast, but the processing of each frame is not required. I hope to establish an asynchronous scenario to skip, rather than block and wait, when slow clients process messages.. At present, messages will accumulate in the slow client. please Is there any way to solve this problem

**Comment by aaugustin** [comment]
See https://websockets.readthedocs.io/en/stable/topics/broadcast.html#per-client-queues.
