### ISSUE TITLE
Websocket 10 raises NegotiationError for permessage-deflate 

### ISSUE THREAD

**Issue by HenryByte** [python-websockets/websockets#1082]
Hey, 
When trying to create a connection to a websocket that doesn't support permessage-deflate, Websocket 10 raises a NegotiationError where Websocket 9.1 does not.

I haven't had the time to investigate the issue in more detail yet, but I assume that Websocket 9.1 falls back to uncompressed communication.

**Comment by aaugustin** [comment]
This sounds more like #1068 (same cause = a poorly implemented server; slightly different symptoms).

**Comment by HenryByte** [comment]
Yeah this looks like it's #1068 Thank you both for the response and sorry for creating a duplicate issue.
