### ISSUE TITLE
[Feature request] Intellisense/autocompletion support when importing the entire websockets module as a whole

### ISSUE THREAD

**Issue by ItsCubeTime** [python-websockets/websockets#1292]
From the docs:

> While Python supports this, tools relying on static code analysis don’t. This breaks auto-completion in an IDE or type checking with > [mypy](https://github.com/python/mypy).
> If you depend on such tools, use the real import paths, which can be found in the API documentation, for example:
> from websockets.client import connect
> from websockets.server import serve

https://websockets.readthedocs.io/en/stable/project/changelog.html#:~:text=While%20Python%20supports,server%20import%20serve

Not that Im familiar with your code base, but language servers like Pylance typically sets the magic variable `TYPE_CHECKING`, so in your code Im guessing you could do something like:
```py
if TYPE_CHECKING:
     ... load module eagerly
else:
    ... load module lazily
```
to avoid breaking code completion.

**Comment by aaugustin** [comment]
Sounds like a plan. Thank you for the suggestion.

**Comment by aaugustin** [comment]
But would require duplicating about 50 lines in `websockets/__init__.py`...

**Comment by ItsCubeTime** [comment]
> But would require duplicating about 50 lines in `websockets/__init__.py`...

😅Yes, to be frank I think its quite horrible from the language server side that it cannot handle dynamic code, but its unlikely to change. I have lots of excessive code in my softwares just to get intellisense working

**Comment by BTOdell** [comment]
I just ran into this issue with lack of intellisense in PyCharm when using the recommended import style:
```python
import websockets
# ...
await websockets.connect()
```
or even:
```python
from websockets import connect
# ...
await connect()
```

The `connect` method has no intellisense.

PyCharm auto-imports `connect` with this:
```python
from websockets.legacy.client import connect
```

Really strange why this project is placing non-legacy code in a package named "legacy".

**Comment by aaugustin** [comment]
The documentation recommends `from websockets.client import connect`.

The `legacy` package makes room for #1245.

**Comment by aaugustin** [comment]
I bit the bullet and duplicated 50 lines :-(

In hindsight, should have done this earlier.

**Comment by ItsCubeTime** [comment]
👍Right decision
