### ISSUE TITLE
How does websockets handle ping-pong keepalive mechanism exactly with ping receivement?

### ISSUE THREAD

**Issue by mick-liu** [python-websockets/websockets#1330]
Dear aaugustin,

I just have a simple question about the following description that you said "websockets takes care of responding to pings with pongs." But I want to know more how does it work? For example, if I have received a ping from our connected server, would it automatically send pong back or something? And how?

Thank you for the work of creating this amazing packages.
Sincerely,.

reference: https://websockets.readthedocs.io/en/stable/faq/common.html#how-do-i-respond-to-pings

**Comment by aaugustin** [comment]
Yes, "websockets takes care of responding to pings with pongs." means that it is done automatically.

It is done according to https://www.rfc-editor.org/rfc/rfc6455#page-37:

> Upon receipt of a Ping frame, an endpoint MUST send a Pong frame in
   response, unless it already received a Close frame.  It SHOULD
   respond with Pong frame as soon as is practical.  Pong frames are
   discussed in [Section 5.5.3](https://www.rfc-editor.org/rfc/rfc6455#section-5.5.3).

>    A Pong frame sent in response to a Ping frame must have identical
   "Application data" as found in the message body of the Ping frame
   being replied to.

**Comment by aaugustin** [comment]
You might be referring to a custom application-level keepalive mechanism while I'm talking of the standard protocol-level mechanism. I will clarify the FAQ.

**Comment by mick-liu** [comment]
Let's say if I have received a ping frame, is it possible to print something to let me know the event happened?
