### ISSUE TITLE
Sync function send() stuck, looks like no way to timeout

### ISSUE THREAD

**Issue by kucharskim** [python-websockets/websockets#1331]
I am running long running Python process, the code under the hood used `python-websockets`. This code uses `send()` and that function takes only one argument a `message`. Shouldn't there be handling of TCP timeout? I am asking as I do a lot of network maintenances on the systems where the code is running and 100% packet loss on the path between webocket servers and clients is normal, during maintenance. I see `send()` stuck in TCP established, without any progress for more than 15 minutes, after the  network maintenance:
```
# netstat -np tcp -f inet
Active Internet connections
Proto   Recv-Q Send-Q  Local Address          Foreign Address        TCP-State
tcp          0      0  192.168.220.76.1604    172.67.71.26.443       ESTABLISHED
```

Should `send()` have a timeout option, or should there be any other way to handle TCP session timeouts in the `python-websockets` code itself?

**Comment by aaugustin** [comment]
You are filing this issue against the wrong repository. The code you linked to uses https://github.com/websocket-client/websocket-client; not websockets.

In websockets, the keepalive mechanism, which is enabled by default, closes the socket after max 40 seconds in the case that you are describing.

**Comment by aaugustin** [comment]
Source: https://github.com/polkascan/py-substrate-interface/blob/1f558e6a5fa9a1ea71ae25211989ebf858a14075/requirements.txt#L1

**Comment by kucharskim** [comment]
Oh, sorry :( Thanks for taking the time and figuring out my mistake. Much appreciated!
