### ISSUE TITLE
Add a `CloseCode` `Enum`

### ISSUE THREAD

**Issue by johnthagen** [python-websockets/websockets#1335]
I was looking for an `Enum` containing definitions of the standard close codes, and couldn't find one. Is this something that could be provided to users? I think an `IntEnum` would be a good way to implement this.

It seemed like this library would be the correct place to implement such an `Enum` for Python users.

### References

- https://www.rfc-editor.org/rfc/rfc6455.html#section-7.4.1
- https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/close
- https://github.com/Luka967/websocket-close-codes
- https://learn.microsoft.com/en-us/dotnet/api/system.net.websockets.websocketclosestatus?view=net-8.0

**Comment by aaugustin** [comment]
In practice, this would mean turning https://github.com/python-websockets/websockets/blob/main/src/websockets/frames.py#L55-L73 into an Enum and making it a public API, similar to [Opcode](https://websockets.readthedocs.io/en/stable/reference/datastructures.html#websockets.frames.Opcode).

**Comment by aaugustin** [comment]
There's a problem, though: extensions can use arbitrary close codes in the 2xxx range and applications can use arbitrary close codes in the 4xxx range, as explained in https://www.rfc-editor.org/rfc/rfc6455.html#section-7.4.2. This cannot be represented with an Enum. How did you plan to handle these cases?

**Comment by johnthagen** [comment]
I was thinking about these as similar in use to [`http.HTTPStatus`](https://docs.python.org/3/library/http.html#http.HTTPStatus) in the standard library.

They don't cover _all_ possible cases, but they provide self-describing names for the standard codes so that user code is clearer and has few magic numbers that can be prone to typo errors.

So in this case, the actual `close()` methods would still all take `int`, but if you as a user explicitly want to use one of these standard codes or compare against them, you have a nice clear, safe way to do that with an `IntEnum`.

For example:

```py
# before:
close(1002)

# after:
close(WebsocketCloseStatus.ProtocolError)

# before
if status == 1002:

# after
if status == WebsocketCloseStatus.ProtocolError:
```

For example, in the Django Channels library, I saw a magic `1000` that could be replaced with a more self-describing `IntEnum`:

https://github.com/django/channels/blob/7e7b71a405db1dbc7509f290b1b158bd07b74c1b/channels/worker.py#L12

User applications can also have these kinds of situations. These applications might also define `Enum`s for custom errors in the 4xxx, but that is out of the scope of something standardized. In these cases they might mix usages of the standard websocket codes with their own `Enum`s.

**Comment by aaugustin** [comment]
The difference is that HTTP error codes cover all possible cases and HTTP libraries crash if they get a code that they don't recognize.

**Comment by aaugustin** [comment]
In other words, I'm not convinced by:

```python
@property
def close_code(self) -> CloseCode | int:
    """Return a CloseCode or, if not recognized, an int."""
```

This doesn't look like a convenient API for the caller.

**Comment by aaugustin** [comment]
To be clear: I recognize that the problem is valid but I don't think that the proposed solution is an improvement over the current situation.

**Comment by johnthagen** [comment]
> In other words, I'm not convinced by:

@aaugustin I also do not think any _APIs_ should change and would not advocate for this change. I was thinking that this `Enum`/`IntEnum` would be used exclusively by end users when referencing these common codes as shown in https://github.com/python-websockets/websockets/issues/1335#issuecomment-1508392907

To me, this is similar to how most HTTP libraries still use an `int` for their API for status codes, here's an example from `httpx`:

- https://github.com/encode/httpx/blob/4b5a92e88e03443c2619f0905d756b159f9f0222/httpx/_models.py#L445-L448

But `httpx` still defines an `IntEnum` for end users to use when setting/checking the `int`s that used in the API:

- https://github.com/encode/httpx/blob/4b5a92e88e03443c2619f0905d756b159f9f0222/httpx/_status_codes.py#L4

But HTTP status codes are still useful for _users_ of the library to avoid magic numbers when possible.

So, to be clear I would only be advocating for defining an `Enum`/`IntEnum` (probably an `IntEnum` given this is explicitly not exhaustive) in this library. None of the APIs would need to change because, as you show, given that it's not exhaustive. I agree that `CloseCode | int` is not a useful type.

> The difference is that HTTP error codes cover all possible cases and HTTP libraries crash if they get a code that they don't recognize.

Is this true? The HTTP libraries I've seen use `int` in their APIs and I've always assumed they would pass back the exact `int` sent over the wire. I suppose we could try sending something like `209` to `httpx`/`requests`/`http.client`.

**Comment by johnthagen** [comment]
> The difference is that HTTP error codes cover all possible cases and HTTP libraries crash if they get a code that they don't recognize.

I tried out a quick Flask/HTTPX application and non exhaustive HTTP status codes are supported.

```py
# server.py
from flask import Flask

app = Flask(__name__)

@app.route("/")
def hello_world():
    return "<p>Hello, World!</p>", 209
```

```py
# client.py
import httpx

response = httpx.get("http://127.0.0.1:5000")
print(response)
print(response.status_code)
```

```
flask --app server run
```

```
py .\client.py
<Response [209 UNKNOWN]>
209
```

**Comment by aaugustin** [comment]
I'm still skeptical about this. Overall, WebSocket close codes are much less important than HTTP status codes.

In ten years of maintaining this library, I never came across any situation where the WebSocket close code matters 🤷

In practice, all you care about is that the connection dropped. Maybe you'll reopen it. The details are only for debugging.

**Comment by johnthagen** [comment]
No problem, definitely understand. I trust your judgement. Thanks for considering. 😄

**Comment by aaugustin** [comment]
Maybe you could tell me a bit more about _why_ you wanted this Enum? What's your use case?

**Comment by aaugustin** [comment]
I sketched a pull request. Now the question is -- to what extent would it make sense to use this enum in the internal implementation?

**Comment by johnthagen** [comment]
PR looks great!

> to what extent would it make sense to use this enum in the internal implementation?

My personal opinion is to use them wherever they improve readability. I would personally default to using the `Enum`s unless there was some compelling reason not to since to they express intent, are less prone to small typos, and are self documenting.

But there is no reason you _have_ to use them everywhere.
