### ISSUE TITLE
Callbacks based support in this library

### ISSUE THREAD

**Issue by tushargoyal22** [python-websockets/websockets#1338]
I have usecases where I need to implement a client on top of websockets for enabling subscriptions to a data, where user will be providing us with the method to execute on receiving a message from the websocket. So is there any wrapper/or support of `on_message` , `on_error` type of thing with this library.

**Comment by aaugustin** [comment]
Callbacks are lower lewel than coroutines, making it trivial to drop from the latter to the former.

```python
async for message in websocket:
    on_message(message)
```

or if it's a coroutine — which you're probably going to need if on_message does I/O:

```python
async for message in websocket:
    await on_message(message)
```

or if you want to fire'n'forget it:

```python
async for message in websocket:
    await asyncio.create_task(on_message(message))
```
