### ISSUE TITLE
Test failure in test_writing_in_recv_events_fails

### ISSUE THREAD

**Issue by aaugustin** [python-websockets/websockets#1339]
See https://github.com/python-websockets/websockets/actions/runs/4725358468/jobs/8383672459#step:5:27

**Comment by likecodingloveproblems** [comment]
It seems the [results](https://github.com/python-websockets/websockets/actions/runs/4725358468/job/12812860881#step:5:27) expired :(

**Comment by aaugustin** [comment]
Logs have expired and I don't remember seeing this happening recently.
