### ISSUE TITLE
Changelogs of websockets library mentions that the implementation based on threading was added in 10.0

### ISSUE THREAD

**Issue by tushargoyal22** [python-websockets/websockets#1340]
https://websockets.readthedocs.io/en/stable/project/changelog.html

I am on `websockets 10.1` and can't import `from websockets.sync.client import connect`
![image](https://user-images.githubusercontent.com/43175862/233400696-d6be1e6c-d5d4-43f6-ad79-593c495c2493.png)

**Comment by aaugustin** [comment]
It's a typo. It was added in 11.0.
