### ISSUE TITLE
Lack of documentation for websocket.sync.client - How to pass authorization headers

### ISSUE THREAD

**Issue by tushargoyal22** [python-websockets/websockets#1341]
I tried passing like `with connect("ws://localhost:8765", extra_headers= headers,max_size=9999999999) as websocket:` 

But it complains `TypeError: connect() got an unexpected keyword argument 'extra_headers'`

Also we should add a separate label for ` websocket.sync.client` PR's/Issues/Bugs , to quickly skim through them, synchronous library is very early stage i believe.

**Comment by aaugustin** [comment]
I believe this is correctly documented. Please make sure you read the version of the docs that matches the API that you are using.
