### ISSUE TITLE
Performance comparison of synchronous client and asyncio client by websockets

### ISSUE THREAD

**Issue by tushargoyal22** [python-websockets/websockets#1342]
Are there any statistics or points mentioning the perfomance comparison between both of them.

**Comment by aaugustin** [comment]
I'm not aware of anything specific to websockets. If you wanted to run a benchmark, the results are completely predictable:

- There will be no measurable difference for a program managing a single client connection.
- For a server managing many connections, a threading-based implementation will perform poorly as the number of connection scales.

This has to do with how kernels manage I/O and threads, not with websockets.

There's a lot of blog posts about asyncio vs. threading. They will apply here.

**Comment by tushargoyal22** [comment]
I am wondering, if we are saying overall `asyncio` is a better choice, then why the `sync client` implementation internally not using asyncio, Ideally it should be synchronous wrapper on top of asyncio client right? 

What are the challenges in that and why is that not considered. 

Why we have written sync client from scratch using `Threading`. It would be super helpful to have such clarity.

**Comment by aaugustin** [comment]
`asyncio` and `threading` are mutually exclusive concurrency & I/O models.

While it is technically possible to mix them e.g. [run_in_executor](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor) this should be avoided as much as possible.

I recommend that you familiarize yourself with these concepts. Once you're on top of the basics, then you can try to contribute to websockets again. Right now, it's obvious that you're missing a lot of prerequisition knowledgde.

**Comment by aaugustin** [comment]
The question is akin to "why don't you build a motorbike as a wrapper around a car". I don't know how to answer that question.

**Comment by aaugustin** [comment]
Maybe this will bring a bit of clarity.

The first stage of websockets was "an asyncio library" (still exists and is still the default implementation).

The second stage of websockets is:

- A Sans-I/O API that contains all the protocol logic, but nothing related to network I/O and concurrency;
- Several API that provide different network I/O and concurrency models:
    - threading (recently added)
    - asyncio (planned, should ultimately the current asyncio implementation, time frame for that is ~ 5 years)
    - trio (not really planned)

**Comment by aaugustin** [comment]
This second stage is akin to "building an engine, and then building either a motorbike or a car around that engine". I can explain why it's built like that. This blog post covers part of the story: https://fractalideas.com/blog/sans-io-when-rubber-meets-road/
