### ISSUE TITLE
Sync client websocket Query

### ISSUE THREAD

**Issue by WrongAnswertoAC** [python-websockets/websockets#1345]
https://websockets.readthedocs.io/en/stable/reference/sync/client.html#websockets.sync.client.ClientConnection

How to check if web socket is closed or not at some point?

Async client has a property called `closed` and we could check using `if self.websocket.closed`, but the sync client has nothing like that. Can we please add it? Whats the way to check if websocket is closed at the moment? 

Also, do we have any slack/discord community to discuss queries like this? where the community can help each other.

**Comment by aaugustin** [comment]
The recommended approach is to call `recv()` or `send()` and to catch `ConnectionClosed`.

Checking the status of the connection then taking action depending on this status is a case of the [LBYL](https://docs.python.org/3/glossary.html#term-LBYL) pattern. This link explains the pitfalls of this approach.

If it's inconvenient to restructure your code in [EAFP](https://docs.python.org/3/glossary.html#term-EAFP) style, can you share your use case so I understand why?

**Comment by tushargoyal22** [comment]
I do have similar usecase.

This is how I will use my code written in SubscriptionManager class

```

client = SubscriptionManager(url= url)
client.subscribe(query=query1)
client.subscribe(query=query2)
```

so basically when the user will invoke `client.subscribe` I need to check if websocket connect is already estabilished and it is not closed, using 
```
        if self.websocket is None or self.websocket.closed:
            self.connect_websocket()
```



```
from websockets.sync.client import connect
from requests_kerberos import HTTPKerberosAuth, DISABLED
from concurrent.futures import ThreadPoolExecutor
from threading import Event

class SubscriptionManager:
    def __init__(self, url: str, max_size: int = 2 ** 30):
        """
        Initialize a SubscriptionManager instance.

        :param url: WebSocket URL to connect to
        :param max_size: Maximum size of incoming messages in bytes (default: 2^30)
        """
        print("Initialize a SubscriptionManager instance. ->", url)
        
        self.websocket = None
        self.url = url
        self.headers = self.get_auth_headers(self.url)
        self.max_size = max_size
        self.subscriptions = {}
        self.subscription_id = 0
        self.mgr = ThreadPoolExecutor(4)
        self.stop_event = Event()


    def subscribe(self, query: str, on_message=None, on_error=None):
        """
        Subscribe to a WebSocket channel and handle incoming messages.

        :param query: Subscription query to send to the WebSocket server
        :param on_message: Optional callback function to handle incoming messages
        :param on_error: Optional callback function to handle errors and connection closure
        """
        
        print("Subscribing to query ->", query)
        def default_on_message(message):
            logging.info(f"Received message on subscription : {message}")

        def default_on_error(error):
            logging.error(f"Error on subscription : {error}")

        on_message = on_message or default_on_message
        on_error = on_error or default_on_error

        if self.websocket is None or self.websocket.closed:
            self.connect_websocket()

        # Generate a unique subscription ID
        subscription_id = len(self.subscriptions)
        self.subscription_id += 1
        # Send the subscription query and save the ID
        action_json = json.dumps(self.get_action(query))
        self.websocket.send(action_json)

        self.subscriptions[subscription_id] = {
            "query": query,
            "on_message": on_message,
            "on_error": on_error
        }
        logging.info(f"Subscribed to query: {query}")
        self.handle_websocket_responses()
       

    def connect_websocket(self):
        """
        Connect to the WebSocket server using the provided URL and headers.
        """
        
        try:
            self.websocket = connect(
                self.url,
                additional_headers=self.headers,
                max_size=self.max_size
            )
            logging.info(f"Connection Estabilished Successfully")
        except Exception as e:
            logging.error(f"Error connecting to websocket: {e}")
            raise e
```


Please share your opinions here.

**Comment by aaugustin** [comment]
When you write:

```python
        if self.websocket is None or self.websocket.closed:
            self.connect_websocket()

        ...

        self.websocket.send(action_json)
```

and you don't handle errors in `send()`, you are clearly assuming that the connection will be open by the time you reach `send()`. This is unsafe. The connection could get closed between these two blocks.

(It would probably be safe with the asyncio API, assuming you don't yield control between these two blocks, but you're using the threading API here so you don't have any control about when your code may yield control to another thread.)

**Comment by aaugustin** [comment]
The documentation of websockets isn't the right place to explain how threads work. There's an abundance of existing educational material answering your question, which is about the difference between preemptive and non-preemptive scheduling.
