### ISSUE TITLE
No type hints

### ISSUE THREAD

**Issue by lukepighetti** [python-websockets/websockets#1346]
I'm on pipenv using websockets `11.0.2` and there are no types to be found anywhere

```python
import websockets

websockets.connect(...) # connect is typed as Any
```

**Comment by aaugustin** [comment]
Does this help? (It's a real question; I don't know if it will help.)
https://websockets.readthedocs.io/en/stable/faq/misc.html#why-does-my-ide-fail-to-show-documentation-for-websockets-apis

**Comment by lukepighetti** [comment]
Yes! Thank you
