### ISSUE TITLE
Blocking task with status callbacks

### ISSUE THREAD

**Issue by lolsborn** [python-websockets/websockets#1348]
I am trying to have an RPC method that will create a resource an on success return a response with the correct rpc id.  In the meantime I want it to send status notifications for that resource based on a callback provided by a third-party library.

Here is a minimal example:
https://gist.github.com/lolsborn/2a4e00a64c830a43a7ccbdd554f39831

The issue I'm having is the callback method is not async, but I need to call websocket.send() which is asynchronous.  I've tried a lot of ways to get this to work, but have been stuck for sometime and would appreciate any insights you might have.

**Comment by aaugustin** [comment]
The bigger problem in your example is calling a blocking method from the event loop. Make sure you run it with `run_in_executor`.

You should be able to schedule async code from sync code with `create_task`. Did you try that?
