### ISSUE TITLE
Can we start two servers in same python program using websockets. Now I am doing this with the help of threading but as a good practice I want to start the two servers without using threading.

### ISSUE THREAD

**Issue by PrafulSinghal-19** [python-websockets/websockets#1358]

**Comment by aaugustin** [comment]
Yes, you can.

This question is more about asyncio than about websockets. See https://websockets.readthedocs.io/en/stable/faq/asyncio.html#how-do-i-run-two-coroutines-in-parallel for some pointers. If you figure out how to run two servers with `asyncio.create_server`, then you can do exactly the same with `websockets.serve`.
