### ISSUE TITLE
AttributeError: module 'websockets' has no attribute 'sync'

### ISSUE THREAD

**Issue by PrafulSinghal-19** [python-websockets/websockets#1360]
I am trying to implement websockets server as a thread and was following the same procedure given in the documentation but I ran into this error, so it would be great if you can help me with this.

Here is my code.

import websockets
import asyncio

def handler(websocket):
    for message in websocket:
        print(f"Message received from server {message}")
        websocket.send(f"Echoed message from client {message}")

if __name__=="__main__":
    with websockets.sync.server.serve(handler,'125.0.0.1',8080) as server:
        server.serve_forever()

**Comment by aaugustin** [comment]
Use `import websockets.sync.server` instead of `import websockets`. This is really a question about Python more than about websockets.
