### ISSUE TITLE
ConnectionResetError after generate a Python binary

### ISSUE THREAD

**Issue by callTx** [python-websockets/websockets#1362]
The `ConnectionResetError` is receiving between a Python binary client `.exe` and a Python *Signalling Server*. 

The following scenario was deployed: 
- The Python client binary was generated using `Pyinstaller` under `Msys2` environment on Windows 11, with  the `websockets` library version `11.0.3` and accessed under `wss` to the *Signalling Server*.
 - The *Signalling Server* was deploy under `wss` using a valid certificate.

Running the Python client script directly on terminal the connection is established.

**Comment by aaugustin** [comment]
I recommend that you try to open a connection with `asyncio.create_connection` instead of `websockets.client.connect`, which removes websockets from the picture. Once that works, passing the same parameters to `websockets.client.connect` or setting up the same environment variables should work.

If it works with `asyncio` and not `websockets`, then maybe it's a `websockets` issue worth discussing here. Else, it's a Python or `asyncio` issue.

**Comment by callTx** [comment]
Sure. 

In this case instead of use
```
self.conn = await websockets.connect("wss://domain:port")
``` 
I used 
```
ssl_options = ssl.create_default_context()
ssl_options.check_hostname = True
ssl_options.verify_mode = ssl.CERT_REQUIRED
self.conn = create_connection("wss://domain:port", sslopt={"cert_reqs": ssl.CERT_REQUIRED, "ssl_version": ssl.PROTOCOL_TLS, "ca_certs": "C:/msys64/mingw64/etc/ssl/cert.pem"})
```

It worked great.

**Comment by aaugustin** [comment]
You used another WebSocket library entirely, which provides non-standard options to configure verification of TLS certificates. I was suggesting to establish a plain TCP connection with asyncio just to figure out standard options.

Something like this should work:

```python
import ssl

ssl_context = ssl.create_default_context()
ssl_context.load_verify_locations("C:/msys64/mingw64/etc/ssl/cert.pem")

asyncio.run(asyncio.get_event_loop().open_connection("host", port, ssl=ssl_context)  # to debug without worrying about websockets
asyncio.run(websockets.connect("wss://domain:port", ssl=ssl_context)  # to use with websockets once it works.
```

Documentation here: https://docs.python.org/3/library/ssl.html#ssl.SSLContext
