### ISSUE TITLE
Websockets for Google Coral DEV Board Mini

### ISSUE THREAD

**Issue by itsover9999** [python-websockets/websockets#1364]
Dear aaugustin,

is there any option to implement websockets in the Google Coral DEV Board Mini? I am currently working on a project to connect a Raspberry Pi to the Google Coral Dev Board Mini, but couldn't find a workaround for the dev board. 

Thank you for your hard work. 
Sincerely

**Comment by aaugustin** [comment]
What is the problem preventing you from installing and running websockets on the coral dev board?

**Comment by itsover9999** [comment]
Thank you very much for your quick reply. I solved the problem and found out that it has nothing to do with the actual package itself. It works great.
