### ISSUE TITLE
Edit button on documentation is broken

### ISSUE THREAD

**Issue by gustavi** [python-websockets/websockets#1365]
1. Go to https://websockets.readthedocs.io/en/stable/
2. Click on "edit" icon (screenshot) 
3. HTTP GET on https://github.com/aaugustin/websockets/edit/bf858ac9a6e047c50614d6990a12345e1f38802c/docs/index.rst
4. Redirect on https://github.com/python-websockets/websockets/edit/bf858ac9a6e047c50614d6990a12345e1f38802c/docs/index.rst
5. GitHub 404

Note: tags (`11.0.3` for example) are also affected.

2 solutions in my mind:
- Replace "edit" by "blob" in URL which is a common "edit on GitHub" behavior: you keep the specific commit in URL
- Replace the commit by "master": you keep the edition interface on GitHub

--

![image](https://github.com/python-websockets/websockets/assets/2736557/398a36c3-8d15-4da8-a1b8-0f04bbe28ecd)

**Comment by aaugustin** [comment]
Thank you for reporting this issue. It is actually an issue with the Furo theme. It was brought up here by another user of Furo: https://github.com/pradyunsg/furo/discussions/114#discussioncomment-6099680

Maybe that discussion goes somewhere, or maybe I'll just look for a way to disable the edit button. I isn't used much, if at all.

**Comment by aaugustin** [comment]
This issue is now tracked there: https://github.com/pradyunsg/furo/issues/668
