### ISSUE TITLE
assyncio

### ISSUE THREAD

**Issue by x011** [python-websockets/websockets#1368]
https://charlesleifer.com/blog/asyncio/

**Comment by aaugustin** [comment]
In case someone lands on this super useful comment (or, even better, #1367) the blog post points out that asyncio isn't suite to most web apps. I agree with this — although I disagree with the scorn in the rhetoric and with the suggestion to rely on gevent.

WebSocket servers have different performance parameters from regular web apps, making asyncio a better fit for this use case. In addition, websockets also provides a synchronous implementation.
