### ISSUE TITLE
the examples seem outdated

### ISSUE THREAD

**Issue by braindevices** [python-websockets/websockets#1370]
For example right now we need `websockets.server.serve` But the example is still based on very [old version](https://github.com/python-websockets/websockets/blob/7b9a53b74c09b27cf0899a28f38f6835c5d141ed/example/quickstart/server.py#L16).

**Comment by aaugustin** [comment]
Thank you for your feedback. I don't think that you posted the right link. Could you confirm where the outdated example is located, please?

**Comment by braindevices** [comment]
Just updated the main post.

I listed several examples here, but those are not all of them. Potentially they may have more outdated stuff in there.

I guess the example should have some way to be tested in CI.

https://github.com/python-websockets/websockets/blob/7b9a53b74c09b27cf0899a28f38f6835c5d141ed/example/quickstart/server.py#L16

https://github.com/python-websockets/websockets/blob/7b9a53b74c09b27cf0899a28f38f6835c5d141ed/example/tutorial/step3/app.py#L193

https://github.com/python-websockets/websockets/blob/7b9a53b74c09b27cf0899a28f38f6835c5d141ed/example/deployment/haproxy/app.py#L21

**Comment by aaugustin** [comment]
These examples aren't really outdated. Convenience imports still work.

The only thing that doesn't work given how they're currently implemented is static analysis (mypy, intellisense, etc.) There's significant pressure from a group who rejects the dynamic nature of Python to change this. I haven't made my mind yet.
