### ISSUE TITLE
Is there a way to get the buffer size?

### ISSUE THREAD

**Issue by LucaNicosia** [python-websockets/websockets#1373]
Hi team,

I wrote a multiproces python application which has N producer and 1 consumer which communicates using websocket. The number of consumer can scale up.

My original idea was to trigger the creation of a new consumer process when 70% of the websocket buffer was used because it meant that the consumer is not fast enough to handle the load generated by the producers.

I didn't find any documentation/discussion about it. Is there a way to know how much of the buffer is used?

**Comment by aaugustin** [comment]
The largest buffer is actually the TCP buffer at the OS level. I don't know how to access it — even from the `socket.socket` object in Python.
