### ISSUE TITLE
Improve docs for Client (threading)

### ISSUE THREAD

**Issue by tushargoyal22** [python-websockets/websockets#1388]
Can we please add docs mentioning the reconnection feature on how can we specify or configure number of retries if websocket connection internally raise Exception related to timeout during handshake.

**Comment by WrongAnswertoAC** [comment]
I dint find in https://websockets.readthedocs.io/en/stable/reference/sync/client.html#

**Comment by aaugustin** [comment]
They already exist: https://websockets.readthedocs.io/en/stable/search.html?q=reconnect

**Comment by aaugustin** [comment]
Sorry I didn't realize you were talking about the threading implementation. See my answer in your other issue.
