### ISSUE TITLE
No sync module in websockets

### ISSUE THREAD

**Issue by twf66** [python-websockets/websockets#1404]
Hi,

I am trying to use the threading server.

When I try to use websockets.sync.server.serve I get an error saying that the reference sync cannot be found:

From IDE:
![image](https://github.com/python-websockets/websockets/assets/147015701/525d41fb-1d34-4878-8470-bcd8774068e7)

From runtime:
![image](https://github.com/python-websockets/websockets/assets/147015701/c495b5d4-d9e1-44d2-bde2-52697917ffa7)

I can see the sync folder exists and contains modules, but I cannot utilize them.
Any help would be appreciated.

**Comment by aaugustin** [comment]
Did you `import websockets.sync.server`?

**Comment by aaugustin** [comment]
I suspect that your problem is the same problem demonstrated below without involving websockets:

```
$ python3
Python 3.10.10 (main, Feb  8 2023, 05:34:50) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib
>>> urllib.parse.quote
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'urllib' has no attribute 'parse'
>>> import urllib.parse
>>> urllib.parse.quote
<function quote at 0x1049689d0>
```

**Comment by twf66** [comment]
@aaugustin  Thank You! Your import suggestion was the answer. I did try various import statements, but just did not have it quite right.
