### ISSUE TITLE
Unable to change port on client-side. Is this a bug or am I stupid?

### ISSUE THREAD

**Issue by JungeWerther** [python-websockets/websockets#1416]
Weirdest bug ever: I cannot seem to change the port on the client side. 

If I run, for example:

```
import websockets
import asyncio

def message():
    with websockets.sync.client.connect("ws://192.168.1.138:8767") as websocket:
        websocket.send("Hello world!")
        message = websocket.recv()
        print(message)

message()

```
(note 8767)

I get an error
```
raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.1.138', 8765)
```
(note 8765)

When I run the server on 8765 instead, I can connect without problem. How is this possible?

When searching through the code I do not find any hardcoded instances of 8765.

Thanks.

**Comment by JungeWerther** [comment]
I'm stupid. Sorry

**Comment by aaugustin** [comment]
You're not stupid. This happened to all of us. Multiple times :-)

**Comment by aaugustin** [comment]
I can delete the issue if you'd like :-)

**Comment by JungeWerther** [comment]
Yes, thanks :)
