### ISSUE TITLE
`test_remote_address` fails

### ISSUE THREAD

**Issue by mtelka** [python-websockets/websockets#1427]
I'm packaging `websockets` for OpenIndiana and when I ran tests I found following failures:
```
======================================================================
FAIL: test_remote_address (tests.sync.test_connection.ClientConnectionTests)
Connection has a remote_address attribute.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "$(BUILD_DIR)/tests/sync/test_connection.py", line 665, in test_remote_address
    self.assertIsNotNone(self.connection.remote_address)
AssertionError: unexpectedly None

======================================================================
FAIL: test_remote_address (tests.sync.test_connection.ServerConnectionTests)
Connection has a remote_address attribute.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "$(BUILD_DIR)/tests/sync/test_connection.py", line 665, in test_remote_address
    self.assertIsNotNone(self.connection.remote_address)
AssertionError: unexpectedly None

----------------------------------------------------------------------
Ran 1297 tests in 9.735s

FAILED (failures=2, skipped=8)
```

**Comment by aaugustin** [comment]
This is likely related to the implementation of [socket.socketpair](https://docs.python.org/3/library/socket.html#socket.socketpair) and/or [socket.socket.getpeername](https://docs.python.org/3/library/socket.html#socket.socket.getpeername) on OpenIndiana.

That's what I'm using for [testing](https://github.com/python-websockets/websockets/blob/33b20e11e86f8490770185c78ed39adab8db4560/tests/sync/test_connection.py#L31C38-L31C38) and how `remote_connection` is [implemented](https://github.com/python-websockets/websockets/blob/33b20e11e86f8490770185c78ed39adab8db4560/src/websockets/sync/connection.py#L110-L121) respectively.

The documentation of `getpeername` acknowledges that it isn't supported on some systems. OpenIndiana may be one of those systems.

Do you a concrete proposal that doesn't make the code or the tests more complex?

**Comment by aaugustin** [comment]
For clarity: to me this is an OpenIndiana and/or Python issue; websockets isn't the right level to fix this.

If there's an easy solution that adds no maintenance cost and help you, of course I'll consider it. The onus of proposing it is on you, though.

**Comment by mtelka** [comment]
> This is likely related to the implementation of [socket.socketpair](https://docs.python.org/3/library/socket.html#socket.socketpair) and/or [socket.socket.getpeername](https://docs.python.org/3/library/socket.html#socket.socket.getpeername) on OpenIndiana.

Could you please suggest some simple test that would prove the problem is either in [socket.socketpair](https://docs.python.org/3/library/socket.html#socket.socketpair) and/or [socket.socket.getpeername](https://docs.python.org/3/library/socket.html#socket.socket.getpeername) on OpenIndiana?

I tried this:
```
$ python
Python 3.9.16 (main, Feb 19 2023, 15:42:40) 
[GCC 10.4.0] on sunos5
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> socket.socketpair()
(<socket.socket fd=5, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0>, <socket.socket fd=4, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0>)
```
But that's apparently not enough.

Thank you.

**Comment by aaugustin** [comment]
Perhaps I should rewrite that test to use a real IP socket.

**Comment by mtelka** [comment]
Yes, exactly, `None`:
```
$ python
Python 3.9.16 (main, Feb 19 2023, 15:42:40) 
[GCC 10.4.0] on sunos5
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> local, remote = socket.socketpair()
>>> local.getpeername()
>>> print(local.getpeername())
None
>>>
```

**Comment by aaugustin** [comment]
Thank you for confirming.

Honestly this test doesn't test anything beyond the existence of a `remote_address` method that doesn't crash. I could remove the assertion that it doesn't return `None`. Anyway the return value is "whatever `getpeername` returns"; that's platform specific.

**Comment by aaugustin** [comment]
I mocked socket methods with platform-specific behavior to make the tests more robust. Hopefully that'll do the job on OpenIndiana. Please let me know if it doesn't.

**Comment by mtelka** [comment]
I just tested websockets 12.0 + b3c51958849c80209b4d68fca081ef3fffc5e2bd and I can confirm that the issue is gone.

Thank you!
