### ISSUE TITLE
websocket connection is closing after some time unexpectedly 

### ISSUE THREAD

**Issue by fti-ravhad** [python-websockets/websockets#1433]
I am using webrtc to live stream media , after some time ice-candidates sending and receiving the connection is closed with below exceptions. 
![Screenshot from 2024-01-18 11-17-17](https://github.com/python-websockets/websockets/assets/146158360/50b74c14-e107-40e6-9033-737233a38633)
The connection works for keepalive_timeout  time only, after that it closes . What are the reasons behind this exceptions 

Python version : 3.10.12
websockets version : 12

**Comment by Kakcalu13** [comment]
I have the exact same issue as this.

What is the solution?

**Comment by aaugustin** [comment]
https://websockets.readthedocs.io/en/stable/project/contributing.html#cryptocurrency-users

(Also -- https://websockets.readthedocs.io/en/stable/faq/client.html#how-do-i-force-the-ip-address-that-the-client-connects-to)

**Comment by aaugustin** [comment]
Oops, sorry — that answer was meant for another issue — my mistake 🙏

**Comment by Kakcalu13** [comment]
That's ok!

You can close this since your doc has the answer already. This answered the main of this issue as well

**Comment by aaugustin** [comment]
The stack trace shows that the other side in closing the websocket connection normally. That's what `received 1000 (OK); then sent 1000 (OK)` means. 1000 is the normal close code.

**Comment by aaugustin** [comment]
I'm glad you could figure it out with the FAQ anyway!

**Comment by fti-ravhad** [comment]
just add asyncio.TimeoutError .. instead of TimeoutError . This worked for me..
