### ISSUE TITLE
No module websockets.imports

### ISSUE THREAD

**Issue by jackswales** [python-websockets/websockets#1453]
When trying to load websockets, I get an error message saying:
 
ModuleNotFoundError: No module named 'websockets.imports'

When looking into the __init__.py script, line 5:

from .imports import lazy_import

an error message says .imports could not be resolved. I've tried a number of ways to overcome this error that has worked on other scripts but nothing I've tried works here.

**Comment by aaugustin** [comment]
Any chance this is the reason? https://websockets.readthedocs.io/en/stable/faq/misc.html#why-do-i-get-the-error-module-websockets-has-no-attribute

**Comment by aaugustin** [comment]
If so, I'll update the FAQ to cover this case too.

**Comment by aaugustin** [comment]
No answer in 4 months -> closing.
