### ISSUE TITLE
iOS and WebSockets: 0 bytes read/no close frame received/code 1006?

### ISSUE THREAD

**Issue by WORMSTweaker** [python-websockets/websockets#1479]
Hello! First of, I would like to thank all the contributors that worked on this library, your work is amazing, and it's really pleasing to work with, by how simple and well documented it is, you all are the best!

Now, to give some context to my issue: I was working on a personal project of mine, which consists of recording snippets of audio from the browser then sending them back via websockets to a server, to be saved. I had _almost_ no issues so far, or at least none that could be resolved by sifting through the doc or the issues, but then came the testing: No issues on desktop browsers, or on android browsers.

And then there is iOS. Which closes my websocket, immediately, as soon as it is opened. To try and debug it, instead of staying on my bigger project, I moved to a simpler echo server/client, and reproduced the issue there.

Setting the logging level to `DEBUG` reveals a `DEBUG ! failing connection with code 1006` message, followed immediately with Python tracebacks, of `0 bytes read on a total of 2 expected bytes`  and `no close frame received or sent`, which can be mitigated with some catching of those respective errors like the documentation explains, but it doesn't fix the underlying issue.

I searched through the issues, opened and closed of the repo, but I didn't find anything mentioning iOS, and the few solutions I tried had no impact.

I have yet to found a solution to this issue, and it is why I am here, to ask for some help. I thank you in advance for your time.

The Python server is running on **Arch Linux**, port 8001,
The client is written in **vanilla JS, no framework**,
The iPhone I'm testing on has **iOS 17.5.1** (latest as of date)
The issue was reproduced on both Safari and Chrome (Firefox simply does nothing after getting in the OPEN state)

Below are attached my Python logs, test Python server, and test JS client, if it can help.

[WebSockets-Stacktrace.txt](https://github.com/user-attachments/files/16203887/WebSockets-Stacktrace.txt)

```python
import asyncio
import ssl
import websockets
import logging

WEBSOCKET_PORT = 8001

###
# On message, print it out
###
async def simpleResponse(websocket):
    #try:
    async for message in websocket:
            print(message)
            await websocket.send("Heartbeat")
    # Catching ConnectionClosedError doesn't resolve the issue
    # except websockets.exceptions.ConnectionClosedError as e:
    #     print("Caught ConnectionClosedError: ", e)
    #     pass


CERT = "web/cert.pem"
KEY = "web/key.pem"
ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
ssl_context.load_cert_chain(CERT, KEY, password="xxx")  # Removed for privacy reasons, ofc
###
# Secure Websocket server
###
async def start_secure_websocket():
    header = {
        'Connection' : 'upgrade',
        'Access-Control-Allow-Origin' : '*'
        }
    logger.info(f"Serving WebSocket server")
    async with websockets.serve(simpleResponse, '', WEBSOCKET_PORT,
                                server_header=None,
                                extra_headers=header, ssl=ssl_context,
                                compression=None, ping_interval=None):
        print("Starting secure websocket")
        await asyncio.Future()


if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG, format='%(asctime)s %(name)s:%(lineno)d %(levelname)s %(message)s')
    logger = logging.getLogger(__name__)
    logger.addHandler(logging.StreamHandler())
    asyncio.run(start_secure_websocket())
```

```javascript
// Register button events
document.getElementById("websocketConnect").addEventListener( 'click', () => {
  connectToWebsocket(document.getElementById("websocketIp").value, document.getElementById("websocketPort").value);
})

document.getElementById("websocketDisconnect").addEventListener( 'click', () => {
  disconnectFromWebsocket();
})


let webSocket;
function connectToWebsocket(ipAddress, port) {
  // Websocket is opened on each button click
  // This is BAD and will not be in the final product
  webSocket = new WebSocket('wss://' + ipAddress + ':' + port);
  webSocket.binaryType = 'blob';

  webSocket.onopen = function(event) {
    document.getElementById("websocketDisconnect").removeAttribute("disabled");
    document.getElementById("websocketConnect").setAttribute("disabled", "");
    console.log("Websocket opened: ", Object.values(event));
    webSocket.send("We are open!");
  }

  webSocket.onmessage = function(event) {
      console.log("Received heartbeat: ", Object.values(event));
  }

  webSocket.onclose = function(event) {
      console.log('WebSocket closed:', Object.values(event));
  };

  webSocket.onerror = function(event) {
      console.error('WebSocket errored!:', event);
      console.error(JSON.stringify(event, null, 4));
  };
}

function disconnectFromWebsocket() {
  document.getElementById("websocketDisconnect").setAttribute("disabled", "");
  document.getElementById("websocketConnect").removeAttribute("disabled");
  // Close the websocket gracefully
  webSocket.close();
}
```

**Comment by aaugustin** [comment]
Your don't need to send a `Connection: upgrade` header — websockets does that.

```python
    header = {
        'Connection' : 'upgrade',
        'Access-Control-Allow-Origin' : '*'
        }
```

Maybe iOS dislikes the duplicate header?

**Comment by WORMSTweaker** [comment]
Ah indeed, I didn't notice that was the case, so I added it myself to try and see if it helped. So removing the duplicate header *seems* to have changed something, on the Python side, the server indicates a `DEBUG = connection is CONNECTING`, on the JS side though `onerror` is triggered followed by the `onclose` event, no message received, no message sent:

![image](https://github.com/user-attachments/assets/0c57d519-02d9-4f48-a33b-5cb027847ad8)

So some progress? At least python-websockets isn't exploding anymore, but now why is iOS closing the connection prematurely?

**Comment by WORMSTweaker** [comment]
Update, and really I'm baffled by how to fix this, and if somebody has an explanation of why this is how things are done on iOS, please enlighten us all.

So, turns out, iOS **HATES** when your websockets are not opened in an asynchronous manner, so, the simple fix for websockets not opening is to define an async function, and await for the websocket to open, which on paper sounds logical, but I haven't found a single ounce of documentation about this.

I tested this on my previous simple echo example, works perfectly, tested on my bigger project, works too, so I suppose the case is closed. I don't know if you want to add more to this since it's not a python-websockets related issue at this point.

**Comment by aaugustin** [comment]
Apple doesn't really want to you keep long-lived TCP connection. They'd rather you use APNS.

**Comment by aaugustin** [comment]
I don't know enough about iOS development to document what you explained in the FAQ (and it's a bit out of scope of what I'm willing to document.) Hopefully other users hitting the same problem with websockets will find this issue and it will put them on the right track.
