### ISSUE TITLE
Client initiated close always runs into `close_timeout`

### ISSUE THREAD

**Issue by baxterjo** [python-websockets/websockets#1487]
Using a simple asyncio client in a context manager I get a closing handshake sequence that looks like this:

```mermaid
sequenceDiagram
    Client->>Server: Close(1000)
    Server-->>Client: ACK
    Server->>Client: Close(1000)
    Client-->>Server: ACK
    Note over Client,Server: 10 seconds passes<br>(default value for close_timeout)
    Client->>Server: FIN-ACK
    Server-->>Client: ACK
```
Changing the close timeout on the client connection adjusts the delay for the FIN-ACK. Is this behavior expected? I'm new to websockets so this might just be something that is expected.

**Comment by aaugustin** [comment]
Of course, if the server is websockets, then that's a bug in websockets. I don't think that's the case because your issue refers only to the client side and because the TCP connection close behaviors are tested quite extensively in websockets' test suite.

**Comment by baxterjo** [comment]
> Of course, if the server is websockets, then that's a bug in websockets. I don't think that's the case because your issue refers only to the client side and because the TCP connection close behaviors are tested quite extensively in websockets' test suite.

The server is written in Rust, so I will look into that. Thanks!
