### ISSUE TITLE
Missing Alert Message before disconnection when a TLS connection error occurs

### ISSUE THREAD

**Issue by m4su6747** [python-websockets/websockets#1503]
Hello, I am testing the secure WebSocket connection.
The server will send an invalid certificate to test the client's disconnection behavior.

The following is the result I captured using Wireshark.
![image](https://github.com/user-attachments/assets/56442b4b-ef50-4d83-9c2e-8bc3217097c3)
The Client immediately disconnected right after the Server Hello which contains a invalid certificate.
Therefore the Server didn't know the reason.

Accroding to the The TLS alert protocol
https://gnutls.org/manual/html_node/The-TLS-Alert-Protocol.html
I expect there to be an Alert Message before the disconnection.

This is another capture with JAVA WebSocket Client.
![image](https://github.com/user-attachments/assets/c7aeab6d-7a0e-4deb-9d77-a7a0f06fe7fb)
Here I can see the Alert (Level: Fatal, Description: Certificate Expired) is sended before the disconnection.

How can I achieve this behavior as well?

**Comment by aaugustin** [comment]
This part are handled by Python's `ssl` module. I think you'd get the same result if you created a client socket directly, without involving websockets -- as shown [here](https://docs.python.org/3/library/ssl.html#socket-creation) or [there](https://docs.python.org/3/library/asyncio-stream.html#asyncio.open_connection).

If so, it's a Python problem, not a websockets problem.

**Comment by m4su6747** [comment]
Thank you for your suggestion.

I found that using the socket module for the connection (socket.create_connection) is able to correctly send Alerts,
![image](https://github.com/user-attachments/assets/28d19f5a-1a7b-46d7-b459-d913ea5a89aa)

while using the asyncio module for the connection (asyncio.open_connection, loop.create_connection) does not send Alerts correctly.
![image](https://github.com/user-attachments/assets/61cbb5d9-a9ac-44ff-9980-24ef34650420)

Yes, it's Python's problem.

**Comment by aaugustin** [comment]
OK - interesting. Looks like this has to do with how asyncio shuts down TLS transports. I encourage you to file this bug against the asyncio module on https://github.com/python/cpython/issues/new/choose
