### ISSUE TITLE
Documentation should clarify that keepalive is supported in async client only

### ISSUE THREAD

**Issue by MarshalX** [python-websockets/websockets#1508]
This documentation page https://websockets.readthedocs.io/en/stable/topics/keepalive.html mentions about `ping_interval` and `ping_timeout` arguments which are only related to async version. I can not find something similar to this

https://github.com/python-websockets/websockets/blob/44ccee17c519ea1397ee28a8ac3a7d7685cd0b89/src/websockets/asyncio/connection.py#L718-L722

in sync version. Thank you!

**Comment by aaugustin** [comment]
Yes it isn't implemented in the sync version (yet). I'll add it to the docs.

**Comment by aaugustin** [comment]
FYI: https://websockets.readthedocs.io/en/stable/reference/features.html is an up-to-date list of which implementation supports which features.

**Comment by MarshalX** [comment]
These tables are awesome! It clarifies all the points. It would be nice to have it near the implementations list where the developer should choose which one to pick. We have that list right on the main page https://websockets.readthedocs.io/en/stable/index.html

> Don’t worry about the opening and closing handshakes, pings and pongs

This statement also could lead to misunderstanding in the sync version until automatic ping and pongs are not implemented

I am glad that this feature will come to a sync version as well. Thank you!

**Comment by aaugustin** [comment]
> It would be nice to have it near the implementations list

Added in d62e4237.

> I am glad that this feature will come to a sync version

For clarity, I don't have a timeline for this — and I'm a bit afraid of adding a new thread for each connection — but it's on my TODO for the project.
