### ISSUE TITLE
How to custom the message pack for ping pong message

### ISSUE THREAD

**Issue by Crypto7816** [python-websockets/websockets#1512]
I’ve read the documentation and know that `websockets` automatically manages `ping-pong`. However, exchanges like Bybit require custom ping-pong messages, as shown in the image below. 
<img width="1052" alt="image" src="https://github.com/user-attachments/assets/be9a5f62-02ec-44cb-983d-4f53faa45ca9">
How can I implement that? I know I can using `websocket.send()`, but is there any way to custome the message and let websockets to handle it automatically?

**Comment by aaugustin** [comment]
https://websockets.readthedocs.io/en/latest/project/support.html#cryptocurrency-users

**Comment by Crypto7816** [comment]
> https://websockets.readthedocs.io/en/latest/project/support.html#cryptocurrency-users

Thanks for replying. I didn't realize you were against BTC.
