### ISSUE TITLE
How would I be able to send bytes data as a text frame.

### ISSUE THREAD

**Issue by percojazz** [python-websockets/websockets#1515]
THe websocket server I am using is asking for text frames but orjson creates bytes directly.
I want to be able to send these bytes directly as text frames, but the way the library works , it seems not possible maybe I have to change the connection object.
Is there a documented way to do this? regards

**Comment by aaugustin** [comment]
Right now you have to use `send(your_json_bytestring.decode())`.

To avoid the useless decoding and encoding, `send()` could gain an `encode` keyword argument, similar to the `decode` argument of `recv()` — whose introduction was motivated by orjson.

Marking as a feature request.

**Comment by aaugustin** [comment]
Based on your Twitter, I'm afraid that https://websockets.readthedocs.io/en/latest/project/support.html#cryptocurrency-users applies, FYI.

**Comment by percojazz** [comment]
Well I am not going to complain because I totally agree with you. Nevertheless, Thanks Aymeric

**Comment by aaugustin** [comment]
NB: I added the feature to the asyncio implementation yesterday. I'm probably going to do the same in the sync implementation soon.

**Comment by percojazz** [comment]
Merci
