### ISSUE TITLE
Nginx Reverse Proxy - Unix Socket - Permission Denied

### ISSUE THREAD

**Issue by AhmedERady** [python-websockets/websockets#1517]
How can nginx read the .sock file if websockets does not give it permission?

**Comment by AhmedERady** [comment]
Is nginx even capable of reading/writing anything outside of /var/www?

**Comment by aaugustin** [comment]
Setting the umask of the Python process with os.umask() should do the job.

nginx can read anywhere, provided the user it's running under has access.
