### ISSUE TITLE
To avoid double work please add byte as posible consumer for connection.respond()

### ISSUE THREAD

**Issue by stalkerg** [python-websockets/websockets#1519]
Seems like new asyncio server process_request can't consume bytes, it's produce extra work.

**Comment by aaugustin** [comment]
You don't have to use the `connection.respond()` helper if you don't like it. You can build a `Response` object and return it.

**Comment by aaugustin** [comment]
The documentation of [Connection.respond](https://websockets.readthedocs.io/en/stable/reference/asyncio/server.html#websockets.asyncio.server.ServerConnection.respond) says "may call" — which implies that you don't have to.
