### ISSUE TITLE
How do I specific another network interface while using websockets.asyncio.client.connect ?

### ISSUE THREAD

**Issue by yo123abxd** [python-websockets/websockets#1529]
Hello, I want to init several connections using distinct network interface, for example: eth0, eth1, eth2, etc. I have browsed the document and issues, but I cannot find any informations.

Please help. Thank you.

**Comment by aaugustin** [comment]
Set a `local_addr` parameter when calling `connect`. It will be passed through to [create_connection](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.create_connection).

**Comment by yo123abxd** [comment]
Thank you for your help. How about websockets.sync.client.connect? I set local_addr when calling websockets.asyncio.client.connect. And it worked. But when I passed local_addr to websockets.sync.client.connect, it raised a TypeError: create_connection() got an unexpected keyword argument 'local_addr'.

**Comment by aaugustin** [comment]
Parameter is called `source_address` and it's passed through to [socket.create_connection](https://docs.python.org/3/library/socket.html#socket.create_connection).
