### ISSUE TITLE
Sesame Package is archived

### ISSUE THREAD

**Issue by simontorres** [python-websockets/websockets#1544]
In the how to integrate with Django, the [tutorial](https://websockets.readthedocs.io/en/stable/howto/django.html#generate-tokens) uses `sesame` to generate tokens. 

When I try to import the `get_token` function I get the following error.

```traceback
from sesame.utils import get_token
Traceback (most recent call last):

  File ~/opt/anaconda3/envs/sandbox/lib/python3.12/site-packages/IPython/core/interactiveshell.py:3577 in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  Cell In[9], line 1
    from sesame.utils import get_token

  File ~/opt/anaconda3/envs/sandbox/lib/python3.12/site-packages/sesame/utils.py:120
    except (UnicodeDecodeError, ValueError), e:
           ^
SyntaxError: multiple exception types must be parenthesize
```

Then checking at the repository, it turns out the package [has been archived](https://github.com/mafrosis/sesame). Unless we were talking of a different package.

**Comment by aaugustin** [comment]
Tutorial uses https://github.com/aaugustin/django-sesame not https://github.com/mafrosis/sesame as shown in https://github.com/python-websockets/websockets/blob/7438b8ebee3f6ef59c15b86d627d32f98f49df8f/docs/howto/django.rst?plain=1#L42.
