### ISSUE TITLE
Issue: Last Message Not Received Before WebSocket Connection Closes in websockets 14.0

### ISSUE THREAD

**Issue by jmtts** [python-websockets/websockets#1545]
# Description

After upgrading to websockets 14.0, I encountered an issue where my code no longer receives the last message sent by the server before the WebSocket connection closes. Previously, the final message from the server would be processed even as the connection was closing. 

# Code Example (simplified)
```python
async def listen(self):
    """Listens for WebSocket messages and processes them."""
    try:
        while True:
            message_raw = await self._session_wss.recv()
            yield self._parse_message(message_raw)
    except (
        websockets.exceptions.ConnectionClosedOK,
    ) as exception:
        return
```

# Expected Behavior
The final message sent by the server should be received and processed before the connection is fully closed. This behavior was observed in previous versions of websockets but is no longer working after upgrading to 14.0.

# Workaround Attempts
1.  Adjusted the exception handling to catch ConnectionClosed exceptions, but this does not capture the last message.
2. Read the FAQs on the topic; I believe I am not leaving the context manager
3.  Attempted adding a separate await recv() in the exception block, which did not resolve the issue.
Environment

# Environment
*  websockets version: 14.0
* Python version: 3.12.5
* Operating System: Ubuntu

**Comment by aaugustin** [comment]
Duplicated of #1538, which is fixed in the main branch.
