### ISSUE TITLE
example/faq/health_check_server.py bug: connection.respond expects str not bytes

### ISSUE THREAD

**Issue by TrevinAvery** [python-websockets/websockets#1546]
I ran the example for ["How do I implement a health check?"](https://websockets.readthedocs.io/en/stable/faq/server.html#how-do-i-implement-a-health-check) and got the error `AttributeError: 'bytes' object has no attribute 'encode'. Did you mean: 'decode'?`

I took a look and found that `ServerConnection.respond` expects the second parameter `text` to be a `str`. It then passes it to `ServerProtocol.reject`, which also expects a string and calls `text.encode()` to convert it to bytes.

The [example](https://github.com/python-websockets/websockets/blob/7438b8ebee3f6ef59c15b86d627d32f98f49df8f/example/faq/health_check_server.py#L9) passes a bytes string to `ServerConnection.respond`, causing this issue.

# Fix

Change
```py
connection.respond(HTTPStatus.OK, b"OK\n")
```
to
```py
connection.respond(HTTPStatus.OK, "OK\n")
```

**Comment by aaugustin** [comment]
Good catch — that's a refactoring mistake on my end.
