### ISSUE TITLE
Cannot access path in websockets.serve handler

### ISSUE THREAD

**Issue by HaroldObasi** [python-websockets/websockets#1557]
I cannot find a way to access the path of a websocket connection, docs say [Receiving the request path in the second parameter of connection handlers is deprecated.](https://websockets.readthedocs.io/en/stable/project/changelog.html#id16)

python version: 3.12.6
websockets version: 14.1

```python
async def handler(websocket: ServerConnection):
  print(websocket.path) ## AttributeError: 'ServerConnection' object has no attribute 'path'

async def main():
    server = await websockets.serve(
        handler,
        "0.0.0.0", 
        9000, 
    )

    print("Server started on 0.0.0.0:9000")

    await server.wait_closed()

if __name__ == "__main__":
    asyncio.run(main())

```

**Comment by aaugustin** [comment]
Check out the release notes for 14.0 and specifically the [upgrade guide](https://websockets.readthedocs.io/en/stable/howto/upgrade.html#path-request-headers-and-response-headers).
