### ISSUE TITLE
DeprecationWarning: websockets.server.serve is deprecated

### ISSUE THREAD

**Issue by snowuyl** [python-websockets/websockets#1565]
I run the sample program provided by websockets GitHub.
The following are log messages.
$ python3 server.py 
/home/snowuyl/samba/workspace_Python/websocket/server.py:4: DeprecationWarning: websockets.server.serve is deprecated
  from websockets.server import serve

The following are source code of WebSocket server.
#!/usr/bin/env python

import asyncio
from websockets.server import serve

async def echo(websocket):
    async for message in websocket:
        await websocket.send(message)

async def main():
    async with serve(echo, "localhost", 8765):
        await asyncio.get_running_loop().create_future()  # run forever

asyncio.run(main())

**Comment by aaugustin** [comment]
See the changelog for version 14.0 and specifically the [upgrade guide](https://websockets.readthedocs.io/en/stable/howto/upgrade.html).
